# Site settings
# To acess a setting: {{ site.myvariable }}

# General
author: Fanny Desarzens
title: Fanny Desarzens
email: your-email@example.com
description: >- # ignore newlines until "baseurl:"
  Auteure
baseurl: "/fannydesarzens"
url: "https://melindafemminis.github.io" 

# Build settings
theme: minima
plugins:
  - jekyll-feed
footerphrase: >- 
  Née en 1993, Fanny Desarzens est diplômée en arts visuels de la  HEAD-Genève. 
  En 2020, sa nouvelle Lignine est lauréate du  concours littéraire organisé à 
  l’occasion des 60 ans de la revue Choisir.

# Define collections: 
collections: 
  ouvrages:
    sort_by: year

# Change page order in the nav bar: 
header_pages:
  - index.md
  - ouvrages.md
  - evenements.md
  - presse.md
  - biographie.md

# Socials
instagram_username: fanny_desarzens
email: email@test.com