# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: Fanny Desarzens
title: Fanny Desarzens
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Auteure
baseurl: "/fannydesarzens" # the subpath of your site, e.g. /blog
url: "https://melindafemminis.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
minima: 
  skin: dark

footerphrase: Née en 1993, Fanny Desarzens est diplômée en arts visuels de la  HEAD-Genève. En 2020, sa nouvelle Lignine est lauréate du  concours littéraire organisé à l’occasion des 60 ans de la revue Choisir.

collections: 
  ouvrages:
    sort_by: year

header_pages:
  - index.md
  - ouvrages.md
  - evenements.md
  - presse.md
  - biographie.md

instagram_username: fanny_desarzens
email: email@test.com

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
